spring:
   application:
      name: section
   h2:
      console:
         enabled: true
         path: /h2
   rabbit:
      host: localhost
      port: 15672
      username: guest
      password: guest
server:
   port: 8001
schedule:
   task:
      close: 0 * * * * *
rabbitmq:
   queues:
      exchange: sicredi.exchange
      queue: sicredi.queue
      routingkey: sicredi.routingkey