spring:
   application:
      name: section
   datasource:
      url: jdbc:postgresql://${postgres_host:localhost}:5432/section
      username: postgres
      password: postgres
   jpa:
      hibernate:
         ddl-auto: create
   rabbitmq:
      host: ${rabbit_host:localhost}
server:
   port: 8001
schedule:
   task:
      close: 0 * * * * *
rabbitmq:
   queues:
      exchange: sicredi.exchange
      queue: sicredi.queue
      routingkey: sicredi.routingkey